### ISSUE TITLE
Source Files

### ISSUE THREAD

**Issue by blackketter** [HiboTronix/DiscoBall#1]
This project is awesome.  Will you be providing the source CAD and software files for folks to build upon your excellent work?  

For me, I'd be interested building a version that uses an ESP32 as the controller to connect it to the world.  

Thanks!

**Comment by HiboTronix** [comment]
The schematic and board files may be released after cleanup, It's not a high priority at the moment, but I will let you know if/when it happens :)

In reference to adding an ESP32 inside, I already tried an 8266, unfortunately the balls ground plane acts as a Faraday cage and severely effects WiFi range, you'll be lucky to get 1-2 feet(if any).

If you wanted to confirm this for yourself the Arduino Nano 33 IoT version comes with a UBLOX NINA W102 which is an ESP32, I haven't checked, but it might fit in place of the Nano Every.
